In [14]:
from sklearn.model_selection import KFold
import numpy as np

In [15]:
X = np.random.random(size = (25, 5))
y = np.random.randint(low = 0, high = 2, size = 25)

In [16]:
X

array([[0.95069777, 0.64224146, 0.6739579 , 0.00265258, 0.96123054],
       [0.18692147, 0.82078313, 0.65992763, 0.82097075, 0.67495274],
       [0.72411764, 0.18054101, 0.6742128 , 0.84943073, 0.95112747],
       [0.1729226 , 0.12701238, 0.77857744, 0.0655417 , 0.21059419],
       [0.96884628, 0.85890943, 0.45209844, 0.51304438, 0.01765446],
       [0.59279915, 0.32504051, 0.99242136, 0.52513134, 0.16816859],
       [0.45750101, 0.48559379, 0.87443115, 0.68876099, 0.78978041],
       [0.98547609, 0.60582256, 0.05479405, 0.58243729, 0.21339616],
       [0.80064601, 0.56648628, 0.27789129, 0.20993874, 0.25461671],
       [0.98736746, 0.45433669, 0.47657603, 0.28911412, 0.0974422 ],
       [0.95106415, 0.38384294, 0.86043   , 0.08528446, 0.93206643],
       [0.17948964, 0.56418622, 0.62764376, 0.66667082, 0.23600111],
       [0.56981712, 0.07204087, 0.36393267, 0.36335747, 0.43532035],
       [0.45370115, 0.73110602, 0.72068049, 0.25825975, 0.59797148],
       [0.5046856 , 0.62300861, 0.

In [17]:
y

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0])

In [18]:
kf = KFold(n_splits = 5)
for train_index, test_index in kf.split(X):
  print("train data:", train_index, "test data: " , test_index)
# 0 --> 24

train data: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] test data:  [0 1 2 3 4]
train data: [ 0  1  2  3  4 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] test data:  [5 6 7 8 9]
train data: [ 0  1  2  3  4  5  6  7  8  9 15 16 17 18 19 20 21 22 23 24] test data:  [10 11 12 13 14]
train data: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 20 21 22 23 24] test data:  [15 16 17 18 19]
train data: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] test data:  [20 21 22 23 24]


In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression

In [23]:
import pandas as pd

In [24]:
house_df = pd.read_csv('/content/housing.csv')

In [25]:
house_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [44]:
house_df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [45]:
house_df.dropna(inplace = True)

In [46]:
house_df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [47]:
X = house_df.iloc[ :, : 8]
y = house_df['median_house_value']

In [52]:
X

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  
0           322.0       126.0         8.3252  
1          2401.0      1138.0         8.3014  
2           496.0       177.0         7.2574  
3           558.0       219.0         5.6431  
4           565.0       259.0         3.8462  
...           ...         ...            ...  
20635       845.0       330.0         1.5603  
20636       356.0       114.0         2.5568  
20637      1007.0       433.0         1.7000  
20638       741.0       349.0         1.8672  
20639      1387.0       530.0         2.3886  

[20433 rows x 8 columns]

In [28]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [42]:
lr = LinearRegression()

In [51]:
cv_scores = cross_val_score(lr, X, y, cv = 10, scoring = 'r2')

In [53]:
cv_scores

array([0.53115461, 0.64316928, 0.48933681, 0.55966335, 0.6039088 ,
       0.55396891, 0.45344879, 0.48182744, 0.51554848, 0.62247673])

In [54]:
cv_scores.mean()

0.545450319840375

In [ ]:
X.shape

(20640, 8)